# Generated by Django 5.1.4 on 2024-12-06 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_exhibit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='planet',
            field=models.CharField(choices=[('E', 'Great African Museum of Earth - Zimbabwe'), ('M', 'Martian Colony - Russian Frontier'), ('P', 'Pluto Stronghold - Chinese Spaceways')], default='E', max_length=1),
        ),
    ]
